---
sidebar: sidebar 
permalink: docs/concept_hci_clusters.html 
summary: 叢集是由儲存節點集合所組成。一個不需要儲存的叢集至少需要兩個儲存節點。NetApp HCI叢集會以單一邏輯群組的形式出現在網路上、然後可作為區塊儲存設備進行存取。 
keywords: netapp, hci, storage nodes, clusters, two-node cluster, three-node cluster, 2-node cluster, 3-node cluster 
---
= 叢集
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
叢集是一組節點、整體運作、可提供儲存或運算資源。從推出的功能區塊1.8開始NetApp HCI 、您可以使用具有兩個節點的儲存叢集。儲存叢集會以單一邏輯群組的形式出現在網路上、然後可作為區塊儲存設備進行存取。

包含在內的儲存層NetApp HCI 是NetApp Element 由VMware軟體提供、管理層則由NetApp Element 適用於vCenter Server的VMware vCenter外掛程式提供。儲存節點是一種伺服器、其中包含透過Bond10G網路介面彼此通訊的磁碟機集合。每個儲存節點均連接至兩個網路、儲存設備和管理設備、每個都有兩個獨立的連結來提供備援和效能。每個節點都需要每個網路上的IP位址。您可以建立具有新儲存節點的叢集、或是將儲存節點新增至現有叢集、以增加儲存容量和效能。



== 驗證儲存叢集

權威儲存叢集是NetApp混合雲控制系統用來驗證使用者的儲存叢集。

如果您的管理節點只有一個儲存叢集、則它是授權叢集。如果您的管理節點有兩個以上的儲存叢集、其中一個叢集會指派為授權叢集、而且只有該叢集的使用者才能登入NetApp混合雲控制。若要瞭解哪個叢集是授權叢集、您可以使用「Get /mnode/about」API。回應時、「toke_URL」欄位中的IP位址是驗證儲存叢集的管理虛擬IP位址（MVIP）。如果您嘗試以非授權叢集的使用者身分登入NetApp混合雲控制、登入嘗試將會失敗。

許多NetApp混合雲控制功能都是專為搭配多個儲存叢集使用而設計、但驗證和授權卻有其限制。驗證與授權的限制在於、授權叢集的使用者可以在其他綁定至NetApp混合雲控制的叢集上執行動作、即使他們不是其他儲存叢集的使用者。在繼續管理多個儲存叢集之前、您應確保在授權叢集上定義的使用者已在所有其他具有相同權限的儲存叢集上定義。

您可以使用NetApp混合雲控制來管理使用者。

在繼續管理多個儲存叢集之前、您應確保在授權叢集上定義的使用者已在所有其他具有相同權限的儲存叢集上定義。請參閱 link:task_mnode_manage_storage_cluster_assets.html["建立及管理儲存叢集資產"] 以取得有關使用管理節點儲存叢集資產的詳細資訊。



== 閒置容量

如果新增的節點佔叢集總容量的50%以上、則此節點的部分容量將無法使用（「閒置」）、因此符合容量規則。在新增更多儲存容量之前、情況仍會如此。如果新增的大型節點也不遵守容量規則、則先前閒置的節點將不再處於閒置狀態、而新新增的節點則會陷入閒置狀態。容量應一律成對新增、以免發生這種情況。當節點變成閒置狀態時、會拋出適當的叢集故障。



== 雙節點儲存叢集

從推出的功能區塊1.8開始NetApp HCI 、您可以設定具有兩個儲存節點的儲存叢集。

* 您可以使用特定類型的節點來形成雙節點儲存叢集。請參閱 https://library.netapp.com/ecm/ecm_download_file/ECMLP2865021["發行說明NetApp HCI"^]。
+

NOTE: 在雙節點叢集中、儲存節點僅限於配備480GB和960GB磁碟機的節點、且節點必須為相同的機型類型。

* 雙節點儲存叢集最適合小型部署、其工作負載不需仰賴大容量和高效能需求。
* 除了兩個儲存節點之外、雙節點儲存叢集也包含兩NetApp HCI 個*「見證節點」*。
+

NOTE: 深入瞭解 link:concept_hci_nodes.html["見證節點。"]

* 您可以將雙節點儲存叢集擴充為三節點儲存叢集。三節點叢集提供從儲存節點故障中自動修復的功能、可提高恢復能力。
* 雙節點儲存叢集提供與傳統四節點儲存叢集相同的安全功能。
* 雙節點儲存叢集使用的網路與四節點儲存叢集相同。這些網路是NetApp HCI 在部署過程中使用NetApp部署引擎精靈來設定。




=== 儲存叢集仲裁

Element軟體會從所選節點建立儲存叢集、以維護叢集組態的複寫資料庫。參加叢集集合至少需要三個節點、以維持叢集恢復能力的仲裁。雙節點叢集中的見證節點用於確保有足夠的儲存節點、以構成有效的整體仲裁。建立頻道群時、儲存節點優先於見證節點。針對涉及雙節點儲存叢集的最少三節點集合體、會使用兩個儲存節點和一個見證節點。


TIP: 在具有兩個儲存節點和一個見證節點的三節點集合體中、如果一個儲存節點離線、叢集就會進入降級狀態。在兩個見證節點中、只有一個可以在集合中作用。第二個見證節點無法新增至集合、因為它會執行備份角色。叢集會保持降級狀態、直到離線儲存節點返回線上狀態、或是替換節點加入叢集為止。

如果見證節點故障、剩餘的見證節點會加入集合、形成三節點集合。您可以部署新的見證節點來取代故障的見證節點。



=== 在雙節點儲存叢集中進行自動修復和故障處理

如果硬體元件在屬於傳統叢集一部分的節點中故障、叢集就能重新平衡元件上的資料、而該元件故障的資料會移至叢集中的其他可用節點。這項自動修復功能無法在雙節點儲存叢集中使用、因為叢集至少必須有三個實體儲存節點可供自動修復。當雙節點叢集中的一個節點故障時、雙節點叢集不需要重新產生第二個資料複本。在剩餘的作用中儲存節點中、會複寫區塊資料的新寫入內容。當更換故障節點並加入叢集時、資料會在兩個實體儲存節點之間重新平衡。



== 具有三個以上節點的儲存叢集

從兩個儲存節點擴充至三個儲存節點、可在發生節點和磁碟機故障時自動修復、但無法提供額外容量、讓叢集更具彈性。您可以使用進行擴充 link:task_hcc_expand_storage.html["NetApp混合雲控制UI"]。從雙節點叢集擴充至三節點叢集時、容量可能會被閒置（請參閱 <<閒置容量>>）。UI精靈會在安裝前顯示有關閒置容量的警告。單一見證節點仍可在儲存節點發生故障時、維持集合仲裁、而第二個見證節點則處於待命狀態。當您將三節點儲存叢集擴充至四節點叢集時、容量和效能會增加。在四節點叢集中、不再需要見證節點來構成叢集仲裁。您最多可擴充至64個運算節點和40個儲存節點。



== 如需詳細資訊、請參閱

* https://www.netapp.com/us/media/tr-4823.pdf["鏈節雙節點儲存叢集| TR-4823 NetApp HCI"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server的VMware vCenter外掛程式NetApp Element"^]
* http://docs.netapp.com/sfe-122/index.jsp["元件與元件軟體文件中心SolidFire"^]

