---
sidebar: sidebar 
permalink: docs/hci_prereqs_witness_nodes.html 
summary: 瞭NetApp HCI 解關於「節點需求」的資訊。 
keywords: netapp, hci, element, Witness Node 
---
= 兩節點儲存叢集的見證節點資源需求
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
支援兩個儲存節點和兩個運算節點的最低安裝大小。NetApp HCI當您使用兩個或三個節點的儲存叢集安裝NetApp HCI 時、您必須注意NetApp HCI 到「見證節點」及其虛擬機器（VM）資源需求。

當儲存叢集使用兩或三個節點時、也會在每個儲存叢集旁部署一對見證節點。見證節點具有下列VM資源需求：

|===
| 資源 | 需求 


| VCPU | 4. 


| 記憶體 | 12GB 


| 磁碟大小 | 67GB 
|===
在雙節點或三節點儲存叢集中、僅支援某些儲存節點機型。NetApp HCI如需更多資訊、請參閱NetApp HCI 《發行說明》以瞭解您的更新版本。

|===


 a| 
*最佳實務做法：*設定見證節點VM使用運算節點的本機資料存放區（預設為NDE）、不要在共享儲存區（例如SolidFire 、靜態儲存磁碟區）上設定。若要防止VM自動移轉、請將見證節點VM的Distributed Resource Scheduler（DRS）自動化層級設為*已停用*。如此可防止在同一個運算節點上執行見證節點、並建立非高可用度（HA）配對組態。

|===

NOTE: 當安裝過程安裝見證節點時NetApp HCI 、VM範本會儲存在VMware vCenter中、您可以在見證節點意外移除、遺失或毀損時、使用該範本來重新部署見證節點。如果您需要更換裝載見證節點的故障運算節點、也可以使用範本來重新部署見證節點。如需相關指示、請參閱「*重新部署兩節點和三節點儲存叢集的見證節點*」一節 link:task_hci_h410crepl.html["請按這裡"^]。



== 如需詳細資訊、請參閱

https://docs.netapp.com/us-en/vcp/index.html["vCenter Server的VMware vCenter外掛程式NetApp Element"^]
