---
sidebar: sidebar 
permalink: docs/task_hci_credentials_vcenter_esxi.html 
summary: 在安裝過程中、您可以針對由NetApp混合雲控制管理的運算節點、變更vCenter和ESXi主機的認證資料。NetApp HCI 
keywords: netapp, hci, password, credential, vcenter, esxi, hybrid cloud control 
---
= 更新vCenter和ESXi認證資料
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
為了維護NetApp混合雲控制功能的完整功能、以利NetApp HCI 您進行VMware vCenter和ESXi主機上的安裝、當您變更認證資料時、也需要更新管理節點上資產服務中的認證資料。

.關於這項工作
NetApp混合雲控制系統可與vCenter及執行VMware vSphere ESXi的個別運算節點通訊、以擷取儀表板的資訊、並促進韌體、軟體和驅動程式的循環升級。NetApp混合雲控制及其管理節點上的相關服務會使用認證（使用者名稱/密碼）來驗證VMware vCenter和ESXi。

如果這些元件之間的通訊失敗、NetApp混合雲控制和vCenter會在發生驗證問題時顯示錯誤訊息。如果NetApp Hybrid Cloud Control無法在NetApp HCI 安裝過程中與相關的VMware vCenter執行個體通訊、則會顯示紅色錯誤橫幅。VMware vCenter會顯示個別ESXi主機的ESXi帳戶鎖定訊息、這是因為使用過時認證的NetApp混合雲控制。

其中的管理節點NetApp HCI 是指使用下列名稱的這些元件：

* 「控制器資產」是與NetApp HCI 您的安裝有關的vCenter執行個體。
* 「運算節點資產」是NetApp HCI 指您安裝的ESXi主機。


在NetApp HCI 使用NetApp部署引擎初始安裝時、管理節點會儲存您為vCenter指定的管理使用者認證、以及ESXi伺服器上的「root」帳戶密碼。



== 使用管理節點REST API更新vCenter密碼

請依照步驟更新控制器資產。請參閱 link:task_mnode_edit_vcenter_assets.html["檢視或編輯現有的控制器資產"]。



== 使用管理節點REST API更新ESXi密碼

.步驟
. 若要取得管理節點REST API使用者介面的總覽、請參閱 link:task_mnode_work_overview_API.html["管理節點REST API使用者介面總覽"]。
. 存取管理節點上用於管理服務的REST API UI：
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
+
將管理網路上管理節點的IP>位址取代NetApp HCI 為用於支援的管理網路。

. 按一下*授權*或任何鎖定圖示、然後完成下列步驟：
+
.. 輸入NetApp SolidFire 的叢集管理使用者名稱和密碼。
.. 輸入用戶端ID為「mnode-client」。
.. 按一下*授權*開始工作階段。
.. 關閉視窗。


. 在REST API UI中、按一下*「Get Ride/Assets / compute _nodes」。
+
這會擷取儲存在管理節點中的運算節點資產記錄。

+
以下是UI中此API的直接連結：

+
[listing]
----
https://<ManagementNodeIP>/mnode/#/assets/routes.v1.assets_api.get_compute_nodes
----
. 按一下*試用*。
. 按一下*執行*。
. 從回應本文中、找出需要更新認證的運算節點資產記錄。您可以使用「IP」和「host_name」內容來尋找正確的ESXi主機記錄。
+
[listing]
----
"config": { },
"credentialid": <credential_id>,
"hardware_tag": <tag>,
"host_name": <host_name>,
"id": <id>,
"ip": <ip>,
"parent": <parent>,
"type": ESXi Host
----
+

NOTE: 下一步使用運算資產記錄中的「父」和「識別碼」欄位來參照要更新的記錄。

. 設定特定的運算節點資產：
+
.. 按一下「*放置/assets /｛asset_id｝/運算節點/｛compute _id｝*」。
+
以下是UI中API的直接連結：

+
[listing]
----
https://<ManagementNodeIP>/mnode/#/assets/routes.v1.assets_api.put_assets_compute_id
----
.. 按一下*試用*。
.. 輸入含有「父」資訊的「asset_id」。
.. 輸入含有「id」資訊的「company_id」。
.. 修改使用者介面中的要求本文、以便只更新運算資產記錄中的密碼和使用者名稱參數：
+
[listing]
----
{
"password": "<password>",
"username": "<username>"
}
----
.. 按一下*執行*。
.. 驗證回應是否為HTTP 200、這表示新認證資料已儲存在參考的運算資產記錄中


. 針對需要以新密碼更新的其他運算節點資產、重複上述兩個步驟。
. 瀏覽至 https://<mNode_ip>/inventory/1/[]。
+
.. 按一下*授權*或任何鎖定圖示、然後完成下列步驟：
+
... 輸入NetApp SolidFire 的叢集管理使用者名稱和密碼。
... 輸入用戶端ID為「mnode-client」。
... 按一下*授權*開始工作階段。
... 關閉視窗。


.. 在REST API UI中、按一下「* Get /Installations *（*取得/安裝*）」。
.. 按一下*試用*。
.. 從「重新整理說明」下拉式清單中選取「*實際*」。
.. 按一下*執行*。
.. 驗證回應是否為HTTP 200。


. 等待約15分鐘、讓vCenter中的帳戶鎖定訊息消失。




== 如需詳細資訊、請參閱

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server的VMware vCenter外掛程式NetApp Element"^]

