---
sidebar: sidebar 
permalink: docs/task_hcc_qos_policies.html 
summary: 您可以設定及修改QoS原則、以套用至儲存叢集中的磁碟區。 
keywords: netapp, qos policy, quality of service, qos policies, volumes, element 
---
= 建立及管理Volume QoS原則
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
QoS（服務品質）原則可讓您建立及儲存標準化的服務品質設定、以便套用至許多磁碟區。選取的叢集必須是元素10.0或更新版本才能使用QoS原則、否則無法使用QoS原則功能。


NOTE: 如NetApp HCI 需使用的詳細資訊、請參閱《概念》內容 link:concept_hci_performance.html#qos-policies["QoS原則"] 而非個別Volume link:concept_hci_performance.html["QoS"]。

使用NetApp混合雲控制、您可以完成下列工作來建立及管理QoS原則：

*  a QoS policy
*  a QoS policy to a volume
*  the QoS policy assignment of a volume
*  a QoS policy
*  a QoS policy




== 建立QoS原則

您可以建立QoS原則、並將其套用至應有同等效能的磁碟區。


NOTE: 如果您使用的是QoS原則、請勿在磁碟區上使用自訂QoS。自訂QoS會覆寫及調整Volume QoS設定的QoS原則值。

.步驟
. 提供NetApp HCI 支援功能不全的儲存叢集管理員認證資料、以登入NetApp混合雲控制系統。
. 從儀表板展開儲存叢集的功能表。
. 選擇*儲存>磁碟區*。
. 按一下「* QoS原則*」索引標籤。
. 按一下「*建立原則*」。
. 輸入* Policy Name*。
+

TIP: 使用描述性命名最佳實務做法。如果您的環境中使用多個叢集或vCenter Server、這點特別重要。

. 輸入最小IOPS、最大IOPS和尖峰IOPS值。
. 按一下「*建立QoS原則*」。
+
系統會針對原則產生系統ID、而原則會顯示在QoS原則頁面上、並顯示其指派的QoS值。





== 將QoS原則套用至磁碟區

您可以使用NetApp混合雲控制、將現有的QoS原則指派給Volume。

您要指派的QoS原則已經存在  a QoS policy,已建立。

本工作說明如何透過變更個別Volume的設定、將QoS原則指派給該磁碟區。最新版本的NetApp混合雲控制系統沒有適用於多個Volume的大量指派選項。在未來版本中提供大量指派功能之前、您可以使用元素Web UI或vCenter外掛程式UI來大量指派QoS原則。

.步驟
. 提供NetApp HCI 支援功能不全的儲存叢集管理員認證資料、以登入NetApp混合雲控制系統。
. 從儀表板展開儲存叢集的功能表。
. 選擇*儲存>磁碟區*。
. 單擊要修改的Volume旁邊的* Actions（操作）*菜單。
. 在產生的功能表中、選取*編輯*。
. 在對話方塊中、啟用*指派QoS原則*、然後從下拉式清單中選取要套用至所選磁碟區的QoS原則。
+

NOTE: 指派QoS會覆寫先前套用的任何個別Volume QoS值。

. 按一下「 * 儲存 * 」。
+
「總覽」頁面上會顯示更新的Volume與指派的QoS原則。





== 變更Volume的QoS原則指派

您可以從磁碟區移除QoS原則指派、或選取不同的QoS原則或自訂QoS。

您要修改的Volume是  a QoS policy to a volume,已指派 QoS原則。

.步驟
. 提供NetApp HCI 支援功能不全的儲存叢集管理員認證資料、以登入NetApp混合雲控制系統。
. 從儀表板展開儲存叢集的功能表。
. 選擇*儲存>磁碟區*。
. 單擊要修改的Volume旁邊的* Actions（操作）*菜單。
. 在產生的功能表中、選取*編輯*。
. 在對話方塊中、執行下列其中一項：
+
** 停用*指派QoS原則*、並修改個別Volume QoS的*最小IOPS *、*最大IOPS *和*爆發IOPS *值。
+

NOTE: 停用QoS原則時、除非另有修改、否則磁碟區會使用預設的QoS IOPS值。

** 從下拉式清單中選取不同的QoS原則、以套用至選取的Volume。


. 按一下「 * 儲存 * 」。
+
更新的Volume會顯示在「總覽」頁面上。





== 編輯QoS原則

您可以變更現有QoS原則的名稱、或編輯與原則相關的值。變更QoS原則效能值會影響與原則相關聯之所有磁碟區的QoS。

.步驟
. 提供NetApp HCI 支援功能不全的儲存叢集管理員認證資料、以登入NetApp混合雲控制系統。
. 從儀表板展開儲存叢集的功能表。
. 選擇*儲存>磁碟區*。
. 按一下「* QoS原則*」索引標籤。
. 單擊要修改的QoS策略旁邊的* Actions（操作）*菜單。
. 按一下 * 編輯 * 。
. 在「*編輯QoS原則*」對話方塊中、變更下列一項或多項：
+
** *名稱*：QoS原則的使用者定義名稱。
** *最小IOPS *：保證磁碟區IOPS的最小數量。預設值= 50。
** *最大IOPS *：磁碟區允許的最大IOPS數。預設值= 15、000。
** *爆發IOPS *：在一段短時間內、磁碟區允許的最大IOPS數。預設值= 15、000。


. 按一下「 * 儲存 * 」。
+
更新後的QoS原則會顯示在QoS原則頁面上。

+

TIP: 您可以按一下「*作用中磁碟區*」欄中的連結、以顯示指派給該原則之磁碟區的篩選清單。





== 刪除QoS原則

您可以刪除不再需要的QoS原則。刪除QoS原則時、所有指派原則的磁碟區都會保留先前由原則定義的QoS值、但會保留個別Volume QoS。與刪除的QoS原則的任何關聯都會移除。

.步驟
. 提供NetApp HCI 支援功能不全的儲存叢集管理員認證資料、以登入NetApp混合雲控制系統。
. 從儀表板展開儲存叢集的功能表。
. 選擇*儲存>磁碟區*。
. 按一下「* QoS原則*」索引標籤。
. 單擊要修改的QoS策略旁邊的* Actions（操作）*菜單。
. 按一下*刪除*。
. 確認行動。


[discrete]
== 如需詳細資訊、請參閱

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server的VMware vCenter外掛程式NetApp Element"^]
* https://docs.netapp.com/us-en/element-software/index.html["零件與元件軟體文件SolidFire"^]

