---
sidebar: sidebar 
permalink: docs/task_hcc_expand_storage.html 
summary: 完成靜態部署之後NetApp HCI 、您可以NetApp HCI 使用NetApp混合雲控制來擴充及設定靜態儲存資源。 
keywords: netapp, hci, on premise, expand, storage, cluster 
---
= 擴充NetApp HCI 功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
完成靜態部署之後NetApp HCI 、您可以NetApp HCI 使用NetApp混合雲控制來擴充及設定靜態儲存資源。

.開始之前
* 請確定現有節點所在的網路區段中有可用且未使用的IPv4位址（每個新節點必須安裝在與其類型現有節點相同的網路上）。
* 確保您擁有下列SolidFire 任一類型的不二儲存叢集帳戶：
+
** 初始部署期間建立的原生系統管理員帳戶
** 具有叢集管理、磁碟機、磁碟區和節點權限的自訂使用者帳戶


* 請確定您已對每個新節點執行下列動作：
+
** 請遵循、將新節點安裝在NetApp HCI 更新機箱中 link:task_hci_installhw.html["安裝說明"]。
** 連接纜線並開啟新節點


* 請確定您擁有已安裝儲存節點的管理IPv6位址。您可以在NetApp Element vCenter Server適用的「VMware vCenter伺服器NetApp Element 」的*《VMware vCenter管理*》>*「叢集*」>「*節點*」索引標籤中找到IP位址。
* 確保每個新節點使用與現有儲存設備或運算叢集相同的網路拓撲和佈線。



TIP: 擴充儲存資源時、儲存容量應平均分配至所有機箱、以獲得最佳可靠性。

.步驟
. 在網頁瀏覽器中開啟管理節點的IP位址。例如：
+
[listing]
----
https://<ManagementNodeIP>
----
. 提供NetApp HCI 不實的儲存叢集管理員認證資料、以登入NetApp混合雲控制系統。
. 按一下介面右上角的*展開*。
+
瀏覽器會開啟NetApp部署引擎。

. 提供本機 NetApp HCI 儲存叢集管理員認證、以登入 NetApp 部署引擎。
+

NOTE: 您無法使用輕量型目錄存取傳輸協定認證登入。

. 在「*歡迎*」頁面上、按一下「*否*」、然後按一下「*繼續*」。
. 在*可用的Inventory（庫存）*頁面上、選取您要新增的儲存節點、然後按一下* Continue（繼續）*。
. 在「*網路設定*」頁面上、從初始部署中偵測到部分網路資訊。每個新的儲存節點都會依序號列出、您需要為其指派新的網路資訊。針對每個新的儲存節點、請完成下列步驟：
+
.. *主機名稱*：NetApp HCI 如果支援功能偵測到命名前置碼、請從偵測到的命名前置碼欄位複製前置碼、然後將其插入為您在「主機名稱」欄位中新增的唯一主機名稱前置碼。
.. *管理位址*：輸入管理網路子網路內新儲存節點的管理IP位址。
.. *儲存設備（iSCSI）IP位址*：輸入iSCSI網路子網路內新儲存節點的iSCSI IP位址。
.. 按一下 * 繼續 * 。
+

NOTE: 驗證輸入的IP位址可能需要一些時間。NetApp HCI當IP位址驗證完成時、「Continue（繼續）」按鈕會變為可用狀態。



. 在「網路設定」區段的「* Review *」頁面上、新節點會以粗體顯示。若要變更任何區段、請執行下列步驟：
+
.. 按一下該區段的*編輯*。
.. 完成後、按一下任何後續頁面上的*繼續*、即可返回「檢閱」頁面。


. *選用*：如果您不想將叢集統計資料與支援資訊傳送至NetApp託管Active IQ 的支援服務器、請清除最終核取方塊。
+
這會停用NetApp HCI 實時健全狀況和診斷監控功能來監控不實時狀況。停用此功能可讓NetApp主動支援NetApp HCI 及監控故障偵測、並在正式作業受到影響之前解決問題。

. 按一下「*新增節點*」。
+
您可以監控進度、同時NetApp HCI 更新及設定資源。

. *選用*：確認vCenter Server的Element外掛程式中顯示任何新的儲存節點。
+

NOTE: 如果您將雙節點儲存叢集擴充至四個或更多節點、儲存叢集先前使用的見證節點配對仍會在vSphere中顯示為待命虛擬機器。新擴充的儲存叢集並不會使用這些資源；如果您想回收VM資源、您可以使用這些資源 link:task_hci_removewn.html["手動移除"] 見證節點虛擬機器。



[discrete]
== 如需詳細資訊、請參閱

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server的VMware vCenter外掛程式NetApp Element"^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/["參考資源頁面NetApp HCI"^]

