---
sidebar: sidebar 
permalink: docs/task_mnode_enable_activeIQ.html 
summary: 您可以使用管理節點（mNode）來啟用NetApp Active IQ 的遙測功能和NetApp HCI 遙測功能。 
keywords: netapp, hci, api, enable, active iq, activeiq, hci monitoring 
---
= 啟用Active IQ 支援功能和NetApp HCI 功能性監控
:allow-uri-read: 


[role="lead"]
如果您在安裝或升級期間尚未啟用支援功能的不支援功能、您可以啟用Active IQ 支援功能以NetApp HCI 監控功能的不支援功能。NetApp HCI如果您使用NetApp HCI NetApp Deployment Engine停用遙測功能、可能需要使用此程序。

此收集器服務會將組態資料和元件軟體型叢集效能指標轉送給NetApp支援中心、以進行歷史報告和近乎即時的效能監控。Active IQ Active IQ利用此功能、可將儲存叢集故障轉送至vCenter以發出警示通知。NetApp HCI

.開始之前
* 您的儲存叢集執行NetApp Element 的是不含更新版本的軟件。
* 您已部署執行11.3版或更新版本的管理節點。
* 您可以存取網際網路。無法從沒有外部連線的黑暗站台使用此收集器服務。Active IQ


.步驟
. 取得安裝的基礎資產ID：
+
.. 在管理節點上開啟庫存服務REST API UI：
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
.. 按一下「*授權*」、然後完成下列項目：
+
... 輸入叢集使用者名稱和密碼。
... 輸入用戶端ID為「mnode-client」。
... 按一下*授權*開始工作階段。
... 關閉視窗。


.. 在REST API UI中、按一下*「Get R針對 性/安裝」*。
.. 按一下*試用*。
.. 按一下*執行*。
.. 從代碼200回應本文中、複製「id」以供安裝之用。
+
[listing, subs="+quotes"]
----
{
  "installations": [
    {
      "_links": {
        "collection": "https://10.111.211.111/inventory/1/installations",
        "self": "https://10.111.217.111/inventory/1/installations/abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x"
      },
      *"id": "abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x",*
----
+

NOTE: 您的安裝具有在安裝或升級期間建立的基礎資產組態。



. 啟動遙測：
+
.. 在管理節點上輸入管理節點IP位址、然後輸入「/mnodes（mnodes）：
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
.. 按一下*授權*或任何鎖定圖示、然後完成下列步驟：
+
... 輸入叢集使用者名稱和密碼。
... 輸入用戶端ID為「mnode-client」。
... 按一下*授權*開始工作階段。
... 關閉視窗。


.. 設定基礎資產：
+
... 按一下「*放置/assets /｛asset_id｝*」。
... 按一下*試用*。
... 在Json有效負載中輸入下列內容：
+
[listing]
----
{
"telemetry_active": true
"config": {}
}
----
... 在「* asse_ID*」中輸入前一個步驟的基礎ID。
... 按一下*執行*。
+
一旦資產發生變更、就會自動重新啟動此服務。Active IQ修改資產會在套用設定之前、造成短暫延遲。





. 如果您尚未這麼做NetApp HCI 、請在NetApp HCI 管理節點的已知資產中新增vCenter控制器資產以進行VMware監控（僅限VMware安裝）和混合雲控制（適用於所有安裝）：
+

NOTE: 需要控制器資產才能NetApp HCI 執行不必要的監控服務。

+
.. 按一下「* POST /Assites/｛asset_id｝/controller*」以新增控制器子資產。
.. 按一下*試用*。
.. 在「* asset_id*」欄位中、輸入您複製到剪貼簿的父基礎資產ID。
.. 輸入所需的有效負載值、並以「type（類型）」做為「vCenter（vCenter）」和vCenter認證。
+
[listing]
----
{
"username": "string",
"password": "string",
"ip": "string",
"type": "vCenter",
"host_name": "string",
"config": {}
}
----
+

NOTE: 「IP」是vCenter IP位址。

.. 按一下*執行*。




[discrete]
== 如需詳細資訊、請參閱

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server的VMware vCenter外掛程式NetApp Element"^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/["參考資源頁面NetApp HCI"^]

