---
sidebar: sidebar 
permalink: docs/task_nde_hci_power_off_storage.html 
summary: 瞭解如何關閉NetApp HCI 各個運算節點的電源。 
keywords: netapp, hci, netapp deployment engine, deployment, vsphere 
---
= 關閉NetApp HCI 適用於某個非系統的儲存資源
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/
:keywords: netapp, hci, netapp deployment engine, deployment, vsphere


[role="lead"]
當您關閉NetApp HCI 用於支援功能的儲存資源時、您需要使用「停機」元素API方法來正確停止儲存節點。

.步驟
關閉運算資源之後、您可以使用網頁瀏覽器來關閉NetApp HCI 該儲存叢集的所有節點。

. 登入儲存叢集、確認您已連線至正確的MVIP。
. （選用）確認主機的所有I/O作業均已停止：
+
.. 使用適當的命令來停止主機端的I/O、以供使用中的一或多個Hypervisor使用。
.. 在叢集UI中、選取*報告*>*總覽*。「叢集輸入/輸出」圖表上不應有任何活動。
.. 在所有I/O作業停止之後、請等待20分鐘再關閉叢集。


. 確認iSCSI工作階段計數為零。
. 瀏覽至*叢集>節點> Active*、並記錄叢集中所有作用中節點的節點ID。
. 若要關閉NetApp HCI 支援功能的儲存叢集、請開啟網頁瀏覽器、然後使用下列URL來叫用關機和停止程序、例如 `{MVIP}` 是NetApp HCI 指不支援的系統及的管理IP位址 `nodes=[]` 陣列包含您在步驟4中記錄的節點ID。例如：
+
[listing]
----
https://{MVIP}/json-rpc/1.0?method=Shutdown&nodes=[1,2,3,4]&option=halt
----
+

NOTE: 您可以在無痕式視窗中執行命令、避免在稍後階段從儲存的URL再次執行。

. 輸入叢集管理員使用者名稱和密碼。
. 驗證API呼叫是否成功傳回、方法是驗證所有儲存叢集節點是否都包含在API結果的「成功」區段中。
+
您已成功關閉所有NetApp HCI 的支援中心儲存節點。

. 關閉瀏覽器或索引標籤、以避免選取「上一步」按鈕並重複API呼叫。


[NOTE]
====
重新啟動叢集時、您必須遵循特定步驟來驗證所有節點是否都已上線：

. 確認所有的「嚴重」嚴重性和 `volumesOffline` 叢集故障已解決。
. 等待10至15分鐘、讓叢集穩定運作。
. 開始啟動主機以存取資料。


如果您想在開啟節點電源並在維護後驗證節點是否正常運作時、留出更多時間、請聯絡技術支援部門以協助延遲資料同步、以避免不必要的Bin同步。

====


== 如需詳細資訊、請參閱

* link:firmware_driver_versions.html["支援的韌體和ESXi驅動程式版本NetApp HCI 、適用於支援NetApp HCI 的VMware及韌體版本、適用於各種儲存節點"]

