---
sidebar: sidebar 
permalink: docs/task_nde_configure_credentials.html 
summary: 瞭解如何在NetApp HCI 部署過程中設定VMware vSphere。 
keywords: netapp, hci, netapp deployment engine, deployment, vsphere 
---
= 設定NetApp HCI 驗證資料
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在部署期間、您可以定義一組認證資料、用於新部署的VMware vSphere環境、NetApp HCI VMware運算與儲存資源、以及管理節點。如果您要在NetApp HCI 現有的vSphere環境中部署VMware、這些認證資料將不會套用至現有的vCenter Server。

.關於這項工作
請記住NetApp HCI 以下關於您在「驗證部署引擎」中設定的認證資訊：

* * NetApp混合雲控制（HCC）或Element Ui*：若要在成功部署後登入NetApp HCC*或Element使用者介面、請使用此部署步驟中指定的使用者名稱和密碼。
* * VMware VCentor*：若要登入vCenter（如果安裝為部署的一部分）、請使用使用者名稱加上字尾「@vSphere.local」或內建的「Administrator @ vsphere.erl」使用者帳戶、以及此部署步驟中指定的密碼。
* * VMware ESXi*：若要登入運算節點上的ESXi、請使用此部署步驟中指定的使用者名稱「root」和相同密碼。


為了與VMware vCenter執行個體互動、NetApp混合雲控制將使用下列其中一項：

* 在部署時安裝的vCenter執行個體上、內建的「Administrator @ vple.l'」使用者帳戶。
* 用來將NetApp HCI VMware vCenter部署連線至現有VMware vCenter Server的vCenter認證資料。


.步驟
. 在*認證*頁面上、於*使用者名稱*欄位中輸入使用者名稱。
. 在*密碼*欄位中輸入密碼。密碼必須符合「*密碼必須包含*」方塊中顯示的密碼條件。
. 在*重新輸入密碼*欄位中確認密碼。
. 按一下 * 繼續 * 。


[discrete]
== 如需詳細資訊、請參閱

* link:firmware_driver_versions.html["支援的韌體和ESXi驅動程式版本NetApp HCI 、適用於支援NetApp HCI 的VMware及韌體版本、適用於各種儲存節點"]
* 若要稍後更新vCenter和ESXi認證、請參閱 link:task_hci_credentials_vcenter_esxi.html["更新vCenter或ESXi認證資料"]。

